server.port: 9411

spring.rabbitmq.host: nghia.tool
spring.rabbitmq.port: 5672

logging:
  level:
    ROOT: INFO
    org.springframework.cloud.sleuth.instrument.messaging.MessagingSpanExtractor: ERROR
    org.springframework.cloud.sleuth.util.ExceptionUtils: ERROR

---
# For deployment in Docker containers
spring:
  profiles: docker

spring.rabbitmq.host: rabbitmq


