server:
  port: 8761
security:
  user:
    password: ${eureka.password}

eureka:
  password: ${SECURITY_USER_PASSWORD:password}
# Configure standalone mode, see http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html#_standalone_mode
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
  server:
  # Disable self-preservation during development, see https://github.com/Netflix/eureka/wiki/Understanding-Eureka-Peer-to-Peer-Communication
    enable-self-preservation: false
    # renewalPercentThreshold: 0.49
    # renewalThresholdUpdateIntervalMs

    # Set this only for this sample service without which starting the instance will by default wait for the default of 5 mins
    wait-time-in-ms-when-sync-empty: 0

    # for the example, set this to zero as we will not have peers to sync up with.
    # Do not set in a real environment with multi-node eureka clusters.
    numberRegistrySyncRetries: 0
    response-cache-update-interval-ms: 1000
logging:
  level.ROOT: INFO